# Generated by Django 6.0.2 on 2026-02-24 12:07

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendox', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goldenuser',
            options={'permissions': [('verify_golden_user', 'Can verify golden users'), ('view_golden_analytics', 'Can view golden user analytics')]},
        ),
        migrations.RemoveField(
            model_name='goldenuser',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='goldenuser',
            name='subscription_date',
        ),
        migrations.RemoveField(
            model_name='goldenuser',
            name='subscription_status',
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='awards',
            field=models.TextField(blank=True, help_text='Awards and recognitions', null=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='bio',
            field=models.TextField(blank=True, help_text='Your professional background', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='golden_covers/'),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 24, 12, 6, 28, 646102, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='followers_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='notable_works',
            field=models.TextField(blank=True, help_text='List of notable works/projects', null=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='profession',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Director', 'Director'), ('Producer', 'Producer'), ('Writer', 'Writer'), ('Cinematographer', 'Cinematographer'), ('Editor', 'Editor'), ('Music Director', 'Music Director'), ('Critic', 'Film Critic'), ('Journalist', 'Entertainment Journalist'), ('Other', 'Other')], default='Other', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='golden_profiles/'),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='social_media_links',
            field=models.JSONField(blank=True, default=dict, help_text='JSON of social media URLs'),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='total_content_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='total_reviews_given',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Admin notes on verification', null=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='verification_status',
            field=models.CharField(choices=[('Pending', 'Pending Verification'), ('Verified', 'Verified Professional'), ('Rejected', 'Verification Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_golden_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='goldenuser',
            name='years_of_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='goldenuser',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='golden_profile', to='recommendox.userprofile'),
        ),
    ]
