# Generated by Django 6.0.2 on 2026-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendox', '0002_alter_goldenuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='poster_url',
            field=models.URLField(blank=True, max_length=50000, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='trailer_url',
            field=models.URLField(blank=True, max_length=50000, null=True),
        ),
    ]
