# Generated by Django 6.0.2 on 2026-02-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendox', '0003_alter_content_poster_url_alter_content_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentott',
            name='watch_url',
            field=models.URLField(blank=True, help_text='URL to watch this content', max_length=50000, null=True),
        ),
    ]
