# Generated by Django 6.0.2 on 2026-03-06 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendox', '0004_alter_contentott_watch_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='views_count',
            field=models.IntegerField(default=0, help_text='Number of times content details viewed'),
        ),
        migrations.AlterField(
            model_name='goldenuser',
            name='profession',
            field=models.CharField(choices=[('Actor', 'Actor'), ('Actress', 'Actress'), ('Director', 'Director'), ('Producer', 'Producer'), ('Writer', 'Writer'), ('Critic', 'Film Critic'), ('Journalist', 'Entertainment Journalist')], max_length=50),
        ),
    ]
