# Generated by Django 6.0.2 on 2026-03-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendox', '0005_content_views_count_alter_goldenuser_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
